"""update provider models

Revision ID: 8962d4d8bc42
Revises: 
Create Date: 2020-09-25 07:32:52.576853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8962d4d8bc42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'billheader', type_='foreignkey')
    op.drop_column('billheader', 'billtype')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billheader', sa.Column('billtype', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'billheader', 'client', ['provider'], ['id'])
    # ### end Alembic commands ###
